### ISSUE TITLE
Add an interface to use `extra-model` inside of Python

### ISSUE THREAD

**Issue by romatik** [wayfair-incubator/extra-model#192]
Right now all of the interfaces we expose assume the workflow like this: `csv` file in -> `csv` file out.
It would be great to expose another interface that takes `pandas` df and returns `pandas` df as an output. We do this internally anyways, so nothing super difficult.

**Comment by rushic24** [comment]
Hi can anyone review this PR for this issue https://github.com/wayfair-incubator/extra-model/pull/198, thanks

**Comment by romatik** [comment]
Solved with #199
