### ISSUE TITLE
Fix broken link to algorithm paper in readme

### ISSUE THREAD

**Issue by fhightower** [wayfair-incubator/extra-model#49]
The link the readme to https://www.aclweb.org/anthology/papers/D18-1384/d18-1384 ends in a 404. Assuming this is not just a problem on my end or a temporary problem with aclweb.org, we should update the link.

**Comment by romatik** [comment]
Thanks for the report!
I've already found this issue and fixed in https://github.com/wayfair-incubator/extra-model/pull/45
