### ISSUE TITLE
Discrepancy between CLI entrypoint and run script

### ISSUE THREAD

**Issue by SanRehmo** [wayfair-incubator/extra-model#56]
There seems to be a discrepancy between [_cli.py](https://github.com/wayfair-incubator/extra-model/blob/main/extra_model/_cli.py) and [_run.py](https://github.com/wayfair-incubator/extra-model/blob/main/extra_model/_run.py) in that `entrypoint_setup()` in `_cli.py` exposes an `output_path` argument to specify where to write the embeddings to but `run()` in `_run.py` does not offer the option to pass that as an argument; there it's hardcoded to `./embeddings`: https://github.com/wayfair-incubator/extra-model/blob/main/extra_model/_run.py#L8

I think we should either 

- add an `embeddings_path` argument to `run()` or 
- remove the `output_path` argument from `entrypoint_setup()`

**Comment by romatik** [comment]
I would definitely go for option 1 - add `embeddings_path` to `run()`. However, I would also change all of the arguments except `input_path` to options so that it actually possible to use different combinations independently.

**Comment by atruslow** [comment]
👋 Hey, I just put up a PR that should fix this, let me know what you think!
